In [7]:
class Dog:
    attr1="mammal"
    attr2="dog"
    
    def fun(self):
        print("I'm a ", self.attr1)
        print("I'm a ", self.attr2)
        
    Rodger = Dog()
    
print(Rodger.attr1)
Rodger.fun()

mammal
I'm a mammal
I'm a dog


In [2]:
class Dog:
 
    # A simple class
    # attribute
    attr1 = "mammal"
    attr2 = "dog"
 
    # A sample method
    def fun(self):
        print("I'm a", self.attr1)
        print("I'm a", self.attr2)
 
 
# Driver code
# Object instantiation
Rodger = Dog()
 
# Accessing class attributes
# and method through objects
print(Rodger.attr1)
Rodger.fun()

mammal
I'm a mammal
I'm a dog


In [8]:
class Person:
    def __init__(self,name):
        self.name=name
    def say_hi(self):
        print('hello, my name is',self.name)
p=Person('Nikhil')
p.say_hi()

hello, my name is Nikhil


In [13]:
class Dog:
    animal='dog'
    def __init__(self,breed, color):
        self.breed=breed
        self.color=color
Rodger=Dog("Pug","brown")
Buzo=Dog("Bulldog","black")
    
print('Rodger details:')
print('Rodger is a', Rodger.animal)
print('Rodger is a', Rodger.breed)
print('Rodger is a', Rodger.color)
    
print('\nBuzo details:')
print('Buzo is a',Buzo.animal)
print('Buzo is a',Buzo.breed)
print('Buzo is a',Buzo.color)
    
print("\nAccessing class variable using class name")
print(Dog.animal)

class Dog:
    animal = 'dog'
    def __init__(self,breed,color):
        self.breed = breed
        self.color = color
Rodger=Dog("Pug", "brown")
Buzo=Dog("Bulldog", "black")
 
print('Rodger details:')
print('Rodger is a', Rodger.animal)
print('Breed: ', Rodger.breed)
print('Color: ', Rodger.color)
 
print('\nBuzo details:')
print('Buzo is a', Buzo.animal)
print('Breed: ', Buzo.breed)
print('Color: ', Buzo.color)
print("\nAccessing class variable using class name")
print(Dog.animal)

Rodger details:
Rodger is a dog
Rodger is a Pug
Rodger is a brown

Buzo details:
Buzo is a dog
Buzo is a Bulldog
Buzo is a black

Accessing class variable using class name
dog
Rodger details:
Rodger is a dog
Breed:  Pug
Color:  brown

Buzo details:
Buzo is a dog
Breed:  Bulldog
Color:  black

Accessing class variable using class name
dog


In [10]:
class Dog:
    animal = 'dog'
    def __init__(self, breed, color):
        self.breed = breed
        self.color = color
Rodger = Dog("Pug", "brown")
Buzo = Dog("Bulldog", "black")
 
print('Rodger details:')
print('Rodger is a', Rodger.animal)
print('Breed: ', Rodger.breed)
print('Color: ', Rodger.color)
 
print('\nBuzo details:')
print('Buzo is a', Buzo.animal)
print('Breed: ', Buzo.breed)
print('Color: ', Buzo.color)
print("\nAccessing class variable using class name")
print(Dog.animal)

Rodger details:
Rodger is a dog
Breed:  Pug
Color:  brown

Buzo details:
Buzo is a dog
Breed:  Bulldog
Color:  black

Accessing class variable using class name
dog


In [14]:
class Dog:
    animal='dog'
    def __init__(self,breed):
        self.breed=breed
    def setColor(self,color):
        self.color=color
    def getColor(self):
        return self.color
Rodger=Dog("pug")
Rodger.setColor("brown")
print(Rodger.getColor())

brown


In [15]:
my_new_car=Car('audi','a4',2016)
my_new_car.fuel_level=5
def update_fuel_level(self, new_level):
    if new_level<=self.fuel_capacity:
        self.fuel_level=new_level
    else:
        print("The tank can't hold that much!")
        

NameError: name 'Car' is not defined

In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [18]:
a

array([1, 2, 3])

In [19]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((2,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [29]:
d=np.arange(10,25,5)

In [30]:
d

array([10, 15, 20])

In [37]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
e=np.full((2,2),7)

In [35]:
e


array([[7, 7],
       [7, 7]])

In [41]:
np.empty((2,3))

array([[0. , 0.4, 0.8],
       [1.2, 1.6, 2. ]])

In [44]:
f=np.eye((2),dtype=int)

In [45]:
f

array([[1, 0],
       [0, 1]])

In [51]:
np.random.random((2,2))

array([[0.9404831 , 0.60816737],
       [0.36346275, 0.77890012]])

In [54]:
np.save('my_array',a)
np.savez('array.npz',a,b)

In [55]:
np.load('my_array.npy')

array([1, 2, 3])

In [56]:
a.shape

(3,)

In [57]:
b.shape

(2, 3)

In [58]:
c.shape

(2, 2, 3)

In [59]:
len(c)

2

In [60]:
len(a)

3

In [61]:
a

array([1, 2, 3])

In [62]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [63]:
len(b)

2

In [64]:
len(c)

2

In [65]:
b.ndim

2

In [66]:
c.ndim

3

In [67]:
a.ndim

1

In [68]:
e

array([[7, 7],
       [7, 7]])

In [69]:
e.size

4

In [70]:
a.size

3

In [72]:
b.size

6

In [73]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [74]:
b.dtype

dtype('float64')

In [75]:
a.dtype

dtype('int32')

In [76]:
a

array([1, 2, 3])

In [78]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [80]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [81]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [82]:
a

array([1, 2, 3])

In [83]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [88]:
d=a+b

In [96]:
d.astype(int)

array([[2, 4, 6],
       [5, 7, 9]])

In [97]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [98]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [99]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [100]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [101]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [102]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [103]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [104]:
e

array([[7, 7],
       [7, 7]])

In [105]:
e.dot(f)

array([[7, 7],
       [7, 7]])

In [106]:
f


array([[1, 0],
       [0, 1]])

In [107]:
a==b

array([[False,  True,  True],
       [False, False, False]])

In [108]:
a<2

array([ True, False, False])

In [110]:
a.sum()

6

In [111]:
a.min()

1

In [113]:
b.max(axis=1)

array([3., 6.])

In [114]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [115]:
b.max(axis=0)

array([4., 5., 6.])

In [116]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [117]:
a.mean()

2.0

In [121]:
a.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [122]:
np.std(b)

1.5920810978785667

In [123]:
h=a.view()

In [124]:
h

array([1, 2, 3])

In [125]:
a

array([1, 2, 3])

In [126]:
np.copy(a)
h=a.copy()

In [127]:
h

array([1, 2, 3])

In [130]:
k=a.sort()

In [131]:
k

In [133]:
i=c.sort(axis=0)

In [134]:
i

In [135]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [136]:
a[2]

3

In [137]:
a

array([1, 2, 3])

In [138]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [146]:
b[0,0]

1.5

In [149]:
a[0:3]

array([1, 2, 3])

In [151]:
b[1:3].astype(int)

array([[4, 5, 6]])

In [152]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [153]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [158]:
c[0,...].astype(int)

array([[1, 2, 1],
       [4, 5, 6]])

In [159]:
i=np.transpose(b)

In [160]:
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [161]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [166]:
i.T.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [185]:
i.reshape(2,3)

array([[1.5, 4. , 2. ],
       [5. , 3. , 6. ]])

In [170]:
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [194]:
c.resize((6,2))

In [196]:
h.resize((3,1))

In [195]:
c

array([[1.5, 2. ],
       [1. , 4. ],
       [5. , 6. ],
       [3. , 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [197]:
h

array([[1],
       [2],
       [3]])

In [198]:
h.T

array([[1, 2, 3]])

In [199]:
h

array([[1],
       [2],
       [3]])

In [202]:
np.append(h,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

In [204]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [207]:
g=np.insert(a,1,5)

In [206]:
a


array([1, 2, 3])

In [208]:
g

array([1, 5, 2, 3])

In [211]:
y=np.delete(a,[1])

In [210]:
a


array([1, 2, 3])

In [212]:
y

array([1, 3])

In [217]:
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [218]:
np.vstack((a,d))

array([[1. , 2. , 3. ],
       [2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [219]:
np.r_[e,f]

array([[7, 7],
       [7, 7],
       [1, 0],
       [0, 1]])

In [220]:
f

array([[1, 0],
       [0, 1]])

In [221]:
e

array([[7, 7],
       [7, 7]])

In [222]:
np.hstack((e,f))

array([[7, 7, 1, 0],
       [7, 7, 0, 1]])

In [ ]:
np.